### ISSUE TITLE
Fix google maps link

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [TNTU-RS-internship/scalhive-theme#44]
## Tasks description
- In footer link to open google maps opens it in the same tab. Idea to add parameter to open this link in another tab. Photo of this link:

![Image](https://github.com/TNTU-RS-internship/scalhive-content/assets/72742712/58a87cac-7264-4cc1-b21e-7aff01d60424)

## Tasks
- [ ] Change `google maps link`.

**Comment by vitalyte** [comment]
@AndriiSmyk  good email address publish [example](https://janeway.systems/contact)
